[package]
name = "bevy-sokoban"
version = "0.1.0"
authors = ["erasin <erasinoo@gmail.com>"]
edition = "2018"

[dependencies]
#bevy = "0.2"
bevy = { git = "https://github.com/bevyengine/bevy" }
rand = "0.7"
dotenv = "0.15"
anyhow = "1"
