[package]
name = "bevy-sokoban"
version = "0.1.0"
authors = ["erasin <erasinoo@gmail.com>"]
edition = "2018"

[dependencies]
# bevy = "0.1.3"
bevy = { path = "/Users/erasin/Development/rust/game/bevy" }
rand = "0.7"
dotenv = "0.15"
